#!/bin/bash
<< task
Deploy a Django App
task

code_clone(){
	echo "cloing the jango app"
	git clone https://github.com/basantgit/django-notes-app-project.git
}

install_requirments(){
	echo "Installing dependinces"
	sudo apt install docker.io  -y
	sudo apt install nginx -y
}

required_restart(){
	sudo chown $USER /var/run/docker.sock
	sudo systemctl enable docker
	sudo systemctl enable nginx
	sudo systemctl restart nginx
	sudo systemctl restart docker
	echo "Install has been completed successfully"
}
deploy(){
	docker build -t notes-app .
	docker run -d -p 8000:8000 notes-app:latest
}
echo "********Deployment Started*************"

if ! code_clone; then
	echo "The code is already exists"
	cd  django-notes-app-project
fi 

if ! install_requirments; then
	echo "Packges not install proprely"
	exit 1
fi
if ! required_restart; then
	echo "System fault identified"
	exit 1
fi
if ! deploy; then
	echo "Some issues found in deployment"
	exit 1
fi

echo "*********Deployment Completed**********"
